apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness
  labels:
    app: aceest-fitness
    environment: production
spec:
  selector:
    app: aceest-fitness
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
